### PR TITLE
🎯 Veterinary Clinic | Start Performance Audit🎯

### PR DESCRIPTION
**Pull request by Rysth**
# 🏅 Features Implemented

List of things that were implemented based on the requirements:

## 📝 General requirements

- ✅ No Linters errors.
- ✅ Used GitFlow correctly.
- ✅ Created a professional `README` file.

## 📝 Project requirements

- ✅ Prepared tables by generating random data.
- ✅ Optimized queries by using `CREATE INDEX`.

### Query 1
image

### Query 2
John-Query-2

### Query 3
John-Query-3

### Query 1
Soban-Query-1

### Query 2
Soban-Query-2

### Query 3
Soban-Query-3

_John Palacios & Soban Syeed_
_Microverse Students_

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @Team👋🏼👋🏼👋🏼👋🏼, 

require_changes


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x]  a pair of screenshots has been included in the PR description with the results of the  EXPLAIN ANALYZE command for each of the queries👍🏼.
- [x] gitflow is used👍🏼.


## Required Changes ♻️

- [ ] Nice job uploading a screenshot showing the effect of `explain analyse` before and after👍🏼. I noticed the for your first query, the execution time was still below 1000ms and it is a requirement that the execution time should be above 1000ms before testing with explain analize. kindly follow the instructions as required👍🏼.
image


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SnakyMz** [comment]
> Hi @Team👋🏼👋🏼👋🏼👋🏼,
> 
> require_changes
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights✅✅✅
> * [x]   a pair of screenshots has been included in the PR description with the results of the  EXPLAIN ANALYZE command for each of the queries👍🏼.
> * [x]  gitflow is used👍🏼.
> 
> ## Required Changes ♻️
> * [ ]  Nice job uploading a screenshot showing the effect of `explain analyse` before and after👍🏼. I noticed the for your first query, the execution time was still below 1000ms and it is a requirement that the execution time should be above 1000ms before testing with explain analize. kindly follow the instructions as required👍🏼.
> 
> image
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hello @Ibizugbe ,
Thanks for the review. But we tested it and even have confirmation in the form of a screenshot Query 1 with an Estimated time of 208.729 ms, which in fact is greater than 1000 ms.
Please look again at the PR. And please share your screenshot about that query.
Thank you

**Comment by Ibizugbe** [comment]
Hello @SnakyMz 👋🏼. Thanks for your feedback, but I think you are making a mistake. as you stated, 208.729 isn't greater than 1000. it is actually lesser.

and it is a requirement that you repeat step 3 untill execution time is greater than 1000ms, then you can use explain analyse 😉.

**Review by shahadat3669 — APPROVED** [review]
Hi @Rysth, @SnakyMz, 

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
✅ Everyone has contributed
✅ Used EXPLAIN ANALYZE command for each
✅ INSERT INTO queries are saved in the data.sql file

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        GitHub
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        LinkedIn
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        Slack
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        Email
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
